trainer:
  epochs: 10
  save_dir: "models/"

optimizer:
  type: "adam"
  params:
    lr: 0.01
    beta: 0.5

dataset:
  name: "comics_ocr_only"
  batch_size: 4

model:
  classname: "TextClozeTextOnlyModel"
  num_tokens: 32100

  max_context_lines: 5
  max_context_size: 100

  encoder_size: 512
  pooler_size: 128

  answer_embed_size: 128
  answer_lines: 3
  answer_max_tokens: 8
