trainer:
  epochs: 10
  batch_size: 4
  save_dir: "models/"

  optimizer:
    type: "adam"
    params:
      lr: 0.01
      beta: 0.5

  dataset:
    name: "comics_ocr_only"
  

model:
  classname: "TextClozeTextOnlyModel"

  num_tokens: 32100
  encoder_size: 512
  pooler_size: 128

  max_context_lines: 5
  max_context_size: 100

  answer_lines: 3
  answer_embed_size: 128
  answer_max_tokens: 8
