trainer:
  save_dir: "models/"
  epochs: 10
  learning_rate: 0.01
  optimizer:
    name: "adam"
    parameters:
      beta: 0.5

dataset:
  path: "dataset/COMICS_ocr_lines.txt"

model:
  num_tokens: 32100
  encoder_size: 512
  pooler_size: 512
  answer_embed_size: 768
  answer_size: 2
  answer_max_tokens: 24
